const express = require('express');
const db = require('../database');
const router = express.Router();

// Public Share Endpoint
router.get('/:token', async (req, res) => {
    const { token } = req.params;
    try {
        // 1. Try New Share (Token)
        const share = await db.getShareByToken(token);


        if (share) {
            // Controleer expiratie (indien ingesteld)
            if (share.expires_at && new Date(share.expires_at) < new Date()) {
                return res.status(410).json({ error: 'Deze deellink is verlopen' });
            }

            // Controleer of de share nog actief is
            if (!share.is_active) {
                return res.status(410).json({ error: 'Deze deellink is niet meer actief' });
            }

            const version = share.model_versions;
            const model = version.models;
            const project = model.projects;

            // Log Activity (Scan)
            await db.logActivity(project.id, 'Gast', 'scan', `Deel-link scan: ${model.name}`);

            const ifcSignedUrl = await db.getFileDownloadUrl(version.storage_path_ifc);
            if (!ifcSignedUrl) return res.status(500).json({ error: 'Kon download link niet genereren' });

            // Update last_accessed
            if (db.supabase) {
                db.supabase.from('shares').update({ last_accessed_at: new Date().toISOString() }).eq('id', share.id).then();
            }

            return res.json({
                filename: model.name,
                projectName: project.name,
                modelUrl: ifcSignedUrl,
                expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString()
            });
        }

        // 2. Try Legacy Public Link (UUID)
        // The QR codes generated by qr.js use a UUID which is stored in public_links table
        const publicLink = await db.getPublicLink(token);

        if (publicLink) {
            if (publicLink.expires_at && new Date(publicLink.expires_at) < new Date()) {
                return res.status(410).json({ error: 'Link is verlopen' });
            }

            const file = publicLink.files;

            // Log Activity (Scan)
            await db.logActivity(publicLink.project_id, 'Guest', 'scan', `QR Scan: ${file.filename}`);

            const modelUrl = await db.getFileDownloadUrl(file.path);
            if (!modelUrl) return res.status(500).json({ error: 'Kon download link niet genereren' });

            return res.json({
                filename: file.filename,
                projectName: "Verouderd Project", // public_links bevatten mogelijk geen projectnaam, eenvoudig gehouden
                modelUrl: modelUrl,
                expiresAt: new Date(Date.now() + 15 * 60 * 1000).toISOString()
            });
        }

        // 3. Not Found
        return res.status(404).json({ error: 'Link niet gevonden of verlopen' });

    } catch (e) {
        console.error('[Share] Toegangsfout:', e);
        res.status(500).json({ error: 'Er is een onverwachte fout opgetreden.' });
    }
});

module.exports = router;
