import { createSupabaseAdminClient } from "../_shared/supabase-admin.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};

const json = (body: Record<string, unknown>, status = 200) =>
  Response.json(body, { status, headers: corsHeaders });

function asOne<T>(value: T | T[] | null | undefined): T | null {
  if (Array.isArray(value)) return value[0] ?? null;
  return value ?? null;
}

function isExpired(value: string | null | undefined): boolean {
  return Boolean(value && Date.parse(value) <= Date.now());
}

function isShareToken(value: string | null): value is string {
  // UUIDs generated by the direct flow and older URL-safe share IDs are both
  // accepted. The token remains a capability checked server-side.
  return Boolean(value && /^[a-zA-Z0-9_-]{12,128}$/.test(value));
}

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }
  if (request.method !== "GET") {
    return json({ error: "Method not allowed" }, 405);
  }

  try {
    const url = new URL(request.url);
    const token = url.searchParams.get("token");
    if (!isShareToken(token)) {
      return json({ error: "Ongeldige viewer-link." }, 400);
    }

    const supabase = createSupabaseAdminClient();

    const { data: share, error } = await supabase
      .from("shares")
      .select(
        "token, is_active, expires_at, model_versions(storage_path_ifc, storage_bucket, file_name, models(name))",
      )
      .eq("token", token)
      .maybeSingle();
    if (error) throw error;

    // Historic shares can predate the is_active column. Only an explicit
    // revocation makes a capability unavailable; the migration normalises
    // legacy NULL values to true as well.
    if (!share || share.is_active === false) {
      return json({ error: "Viewer-link niet gevonden of ingetrokken." }, 404);
    }
    if (isExpired(share.expires_at)) {
      return json({ error: "Viewer-link is verlopen." }, 410);
    }

    const version = asOne<any>(share.model_versions);
    if (!version?.storage_path_ifc) {
      return json({ error: "Viewer-link bevat geen IFC-bestand." }, 404);
    }

    const bucket = version.storage_bucket || "ifc-models";
    const { data: signed, error: signedError } = await supabase.storage
      .from(bucket)
      .createSignedUrl(version.storage_path_ifc, 60 * 15);
    if (signedError || !signed?.signedUrl) {
      return json({ error: "IFC-bestand is niet beschikbaar." }, 404);
    }

    const update = await supabase
      .from("shares")
      .update({ last_accessed_at: new Date().toISOString() })
      .eq("token", share.token);
    if (update.error) {
      console.error("Kon laatst-geopend tijdstip niet bijwerken", update.error);
    }

    const model = asOne<any>(version.models);
    const candidateName = version.file_name || model?.name || "model.ifc";
    const filename = candidateName.toLowerCase().endsWith(".ifc")
      ? candidateName
      : `${candidateName}.ifc`;
    return json({ modelUrl: signed.signedUrl, filename });
  } catch (error) {
    console.error("viewer-link fout", error);
    return json({ error: "Viewer-link kon niet worden opgehaald." }, 500);
  }
});
